### ISSUE TITLE
Doesn't work with 3.0

### ISSUE THREAD

**Issue by wormtreat** [gintonicweb/GintonicCMS#3]
I would really like to use this.... I've been trying for a couple of days and they've now released the official version. I was having no luck in the first place, now I'm getting a new error. Some additional instructions would be nice too, for those who are new to using composer. I don't think it's quite as simple as running one command. Try doing a fresh install and see if it works for you, I doubt it will... 

Many Thanks!

**Comment by Phillaf** [comment]
Hi wormtreat, we are actively working on that CMS as of now and we're aware of various issues. A working version should be released within the next weeks, and it still might take a little more 'till we can call it stable. Out of curiosity, Which feature are you interested the most in?

**Comment by wormtreat** [comment]
Hey Philippe,

Thanks for the reply!! I was looking for a CMS that used cake3 bootstrap3
and jquery... Angular is a bonus. I decided to try yours since it was
lightweight and basically 'the way I would do it'.... I've been using a
cake2-based CMS at my previous job and wanted to start fresh with something
that already had all the basic stuff, page and nav management. I've never
used composer, just done everything manually, so composer is annoying as
hell to me. Particularly when it doesn't work.... I really need to get
something working a.s.a.p. so I was thinking of just pulling code out from
your plugin and sticking it in the base code. Please keep me posted tho.

Thanks!
Evan

**Comment by Phillaf** [comment]
Yeah I think that's the only option for now. You might want to have a look at this branch which is way ahead of the current master branch.
https://github.com/jadavsushil/GintonicCMS

**Comment by wormtreat** [comment]
Cool! Thanks for the tip. I'll give you a heads-up once I get rolling with
it. Maybe I'll have something to contribute eventually.

Thanks,
Evan

**Comment by wormtreat** [comment]
I have a couple of weeks to get a CMS working, maybe a tad more. If there's
anything I can help with please don't hesitate to reach out and give me
direction. I would like to use your plugin and continue to build on top of
it, so I will be happy to share anything useful to you. I am just diving
into cake3 and composer but I've been working with cake2 for some time. In
other words, it looks like I'm going to be working primarily with your code
for the next couple of weeks so If I can help fix transitional issues or
anything, you're welcome to task it to me.

-Evan

**Comment by wormtreat** [comment]
If you use skype, you can find me as "wormtreat"... My primary email is
evan@evansinfo.com and my cell is 626-421-9585. I work from home so I'm
basically available around the clock.

-Evan

**Comment by Phillaf** [comment]
Hi wormheat, I've been working on the cms over the last 2 days to try and make a basic version up. Some help would be greatly appreciated on the project and I am making a priority of having this plugin up and running as quickly as possible.

The main goal of this cms is to provide the core of the application (users / file management, helpers for the front end, provide an administration control panel etc.). Then we can use it as a base to develop plugins according to our tastes.

If you tell me a little more about your needs we can plan accordingly starting right now and make sure that your needs are being covered.

**Comment by Phillaf** [comment]
Closing the issue as the CMS has moved a great way and is now splitted in different plugins with each their own statuses.
